### ISSUE TITLE
Unable to submit blog assignment

### ISSUE THREAD

**Issue by johnsontaiwo** [learn-co-curriculum/ruby-orm#10]
Hi,
I was prevented from submitting my blog assignment with the following error message shown on my screen, even after adding the title. I already saved it as draft but was unable to publish it.
"Your post can't be published. Make sure the first line contains your post title "# formatted like this"."
I will appreciate it if someone can guide me on what to do next.

Thanks.
Johnson.

**Comment by AnnJohn** [comment]
hi @johnsontaiwo sorry for the delay with this. Since this is a technical issue, could you actually file a bug  report? If you click on your profile pic in Learn, you'll see a menu with an option there to report a bug. 

We use this space for issues specifically related to the content in the lessons. Thanks!
